ALTER TABLE NEGOCIACOES_ITENS
ADD CONSTRAINT FK_NEGOCIACOES_ITENS_NEG
FOREIGN KEY (ID_NEGOCIACAO)
REFERENCES NEGOCIACOES(ID)
ON UPDATE CASCADE;

ALTER TABLE NEGOCIACOES_ITENS
ADD CONSTRAINT FK_NEGOCIACOES_ITENS_PRODUTO
FOREIGN KEY (ID_PRODUTO)
REFERENCES PRODUTOS(ID)
ON UPDATE CASCADE;

