ALTER TABLE PRODUTORES_LIMITES
ADD CONSTRAINT FK_PRODUTORES_LIMITES_PROD
FOREIGN KEY (ID_PRODUTOR)
REFERENCES PRODUTORES(ID)
ON UPDATE CASCADE;

ALTER TABLE PRODUTORES_LIMITES
ADD CONSTRAINT FK_PRODUTORES_LIMITES_DIST
FOREIGN KEY (ID_DISTRIBUIDOR)
REFERENCES DISTRIBUIDORES(ID)
ON UPDATE CASCADE;

