ALTER TABLE PRODUTOES_LIMITES
ADD CONSTRAINT FK_PRODUTOES_LIMITES_PROD
FOREIGN KEY (ID_PRODUTOR)
REFERENCES PRODUTORES(ID)
ON UPDATE CASCADE;

ALTER TABLE PRODUTOES_LIMITES
ADD CONSTRAINT FK_PRODUTOES_LIMITES_1
FOREIGN KEY (ID_DISTRIBUIDOR)
REFERENCES DISTRIBUIDORES(ID)
ON UPDATE CASCADE;

