ALTER TABLE NEGOCIACOES
ADD CONSTRAINT FK_NEGOCIACOES_PRODUTOR
FOREIGN KEY (ID_PRODUTOR)
REFERENCES PRODUTORES(ID)
ON UPDATE CASCADE;

ALTER TABLE NEGOCIACOES
ADD CONSTRAINT FK_NEGOCIACOES_DISTRIBUIDOR
FOREIGN KEY (ID_DISTRIBUIDOR)
REFERENCES DISTRIBUIDORES(ID)
ON UPDATE CASCADE;

