INSERT INTO CODIFICACAO (CODIFICACAOID,CDFDESCRICAO,CDF_STATUS,USUARIOID,DATAHORA) VALUES
	 (1,'NEGOCIACAO',0,NULL,NULL),
	 (2,'Pendente',1,NULL,NULL),
	 (3,'Aprovada',1,NULL,NULL),
	 (4,'Concluir',1,NULL,NULL),
	 (5,'Cancelada',1,NULL,NULL);
