CREATE TABLE CREDITO (
  CODIGO SMALLINT NOT NULL,
  PRODUTOR SMALLINT,
  DISTRIBUIDOR SMALLINT,
  VALOR FLOAT,
  NOMEDISTRIBUIDOR VARCHAR(60) CHARACTER SET WIN1252);


ALTER TABLE CREDITO ADD PRIMARY KEY (CODIGO);


SET TERM ^ ;

CREATE TRIGGER BI_CREDITO_CODIGO FOR CREDITO
ACTIVE BEFORE 
  INSERT
POSITION 0
AS
BEGIN
  IF (NEW.CODIGO IS NULL) THEN
      NEW.CODIGO = GEN_ID(CREDITO_CODIGO_GEN, 1);
END^

SET TERM ; ^