CREATE TABLE CREDITO (
  CODIGO INTEGER NOT NULL,
  PRODUTOR INTEGER,
  DISTRIBUIDOR INTEGER,
  VALOR FLOAT,
  NOMEDISTRIBUIDOR VARCHAR(60) CHARACTER SET WIN1252);


SET TERM ^ ;

CREATE TRIGGER BI_CREDITO_CODIGO FOR CREDITO
ACTIVE BEFORE 
  INSERT
POSITION 0
AS
BEGIN
  IF (NEW.CODIGO IS NULL) THEN
      NEW.CODIGO = GEN_ID(CREDITO_CODIGO_GEN1, 1);
END^

SET TERM ; ^