CREATE TABLE DISTRIBUIDOR (
  CODIGO SMALLINT NOT NULL,
  NOME VARCHAR(60) CHARACTER SET WIN1252 COLLATE WIN_PTBR,
  CPFCNPJ VARCHAR(20));


SET TERM ^ ;

CREATE TRIGGER BI_DISTRIBUIDOR_CODIGO FOR DISTRIBUIDOR
ACTIVE BEFORE 
  INSERT
POSITION 0
AS
BEGIN
  IF (NEW.CODIGO IS NULL) THEN
      NEW.CODIGO = GEN_ID(DISTRIBUIDOR_CODIGO_GEN, 1);
END^

SET TERM ; ^