CREATE TABLE NEGOCIACAO_DETALHE (
  CODIGO INTEGER  NOT NULL,
  NEGOCIACAO INTEGER,
  PRODUTO INTEGER);


SET TERM ^ ;

CREATE TRIGGER BI_NEGOCIACAO_DETALHE_CODIGO FOR NEGOCIACAO_DETALHE
ACTIVE BEFORE 
  INSERT
POSITION 0
AS
BEGIN
  IF (NEW.CODIGO IS NULL) THEN
      NEW.CODIGO = GEN_ID(NEGOCIACAO_DETALHE_CODIGO_GEN1, 1);
END^

SET TERM ; ^