CREATE TABLE NEGOCIACAO (
  CODIGO SMALLINT NOT NULL,
  PRODUTOR SMALLINT,
  DISTRIBUIDOR SMALLINT,
  VALOR FLOAT,
  "DATA" DATE,
  STATUS SMALLINT);


ALTER TABLE NEGOCIACAO ADD PRIMARY KEY (CODIGO);


SET TERM ^ ;

CREATE TRIGGER BI_NEGOCIACAO_CODIGO FOR NEGOCIACAO
ACTIVE BEFORE 
  INSERT
POSITION 0
AS
BEGIN
  IF (NEW.CODIGO IS NULL) THEN
      NEW.CODIGO = GEN_ID(NEGOCIACAO_CODIGO_GEN, 1);
END^

SET TERM ; ^