INSERT INTO NUMERACAO (NMRNOMETABELA,SISTEMAID,NMRNUMEROLIVRE,NMRNOMECOLUNA) VALUES
	 ('PRODUTOR',1,1,'PRODUTOR_ID'),
	 ('DISTRIBUIDOR',1,1,'DISTRIBUIDOR_ID'),
	 ('PRODUTO',1,1,'PRODUTO_ID'),
	 ('PROD_DISTRIBUIDOR',1,1,'PROD_DISTRIB_ID'),
	 ('NEGOCIACAO',1,1000,'NEGOCIACAO_ID');
