CREATE TABLE PRODUTOR (
  CODIGO SMALLINT NOT NULL,
  NOME VARCHAR(60) CHARACTER SET WIN1252 COLLATE WIN_PTBR,
  CPFCNPJ VARCHAR(20));


ALTER TABLE PRODUTOR ADD PRIMARY KEY (CODIGO);


SET TERM ^ ;

CREATE TRIGGER BI_PRODUTOR_CODIGO FOR PRODUTOR
ACTIVE BEFORE 
  INSERT
POSITION 0
AS
BEGIN
  IF (NEW.CODIGO IS NULL) THEN
      NEW.CODIGO = GEN_ID(PRODUTOR_CODIGO_GEN, 1);
END^

SET TERM ; ^