CREATE TABLE PRODUTO (
  CODIGO SMALLINT NOT NULL,
  NOME VARCHAR(60) CHARACTER SET WIN1252 COLLATE WIN_PTBR,
  VALOR FLOAT);


ALTER TABLE PRODUTO ADD PRIMARY KEY (CODIGO);


SET TERM ^ ;

CREATE TRIGGER BI_PRODUTO_CODIGO FOR PRODUTO
ACTIVE BEFORE 
  INSERT
POSITION 0
AS
BEGIN
  IF (NEW.CODIGO IS NULL) THEN
      NEW.CODIGO = GEN_ID(PRODUTO_CODIGO_GEN, 1);
END^

SET TERM ; ^